# This workflow will build a Swift project



name: release builder


on:
  workflow_dispatch:




jobs:
  toolchainBuild:
    #needs: mainjob1
    runs-on: macOS-13
    permissions:
        contents: write
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - uses: actions/checkout@v3
  
    #   - name: retrieve output
    #     run: |
    #       echo "${{ needs.mainjob1.outputs.version }}"
    #       echo "${{ needs.mainjob1.outputs.sha }}"

      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install kivy-ios
        run: |
          python3 -m pip install --upgrade pip
          pip3 install https://github.com/kivy/kivy-ios/archive/master.zip
          brew install autoconf automake libtool pkg-config
          brew link libtool
          
    #   - name: generate cookie
    #     run: python3.10 generate_formula.py ${{ needs.mainjob1.outputs.version }} ${{ needs.mainjob1.outputs.sha }}


      - name: toolchain build kivy pillow
        run: |
            mkdir kivy_build
            cd kivy_build
            toolchain build kivy
            toolchain build pillow
            cd ..
      - name: repack build environment
        run: |
            mkdir output
            mv kivy_build/dist/xcframework output/
            mv kivy_build/dist/lib output/
            cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: kivy-output
          path: ./output

  artifact-use-build:
    name: Re-use Artifact
    runs-on: ubuntu-latest
    needs: [toolchainBuild]

    steps:
      #- uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: kivy-output
      - run: |
            ls
