# This workflow will build a Swift project



name: release builder


on:

  push:
    tags: '*'
  
  workflow_dispatch:




jobs:
  toolchainBuild:
    #needs: mainjob1
    runs-on: macOS-13
    permissions:
        contents: write
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - uses: actions/checkout@v3
  
    #   - name: retrieve output
    #     run: |
    #       echo "${{ needs.mainjob1.outputs.version }}"
    #       echo "${{ needs.mainjob1.outputs.sha }}"

      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install kivy-ios
        run: |
          python3 -m pip install --upgrade pip
          pip3 install https://github.com/kivy/kivy-ios/archive/master.zip
          brew install autoconf automake libtool pkg-config
          brew link libtool
          
          chmod 755 restructure.sh  

      - name: toolchain build python3
        run: toolchain build python3
      
      - name: toolchain build kivy
        run: toolchain build kivy
      
      - name: toolchain build pillow
        run: toolchain build pillow
      
      - name: repack build environment
        run: |
            cd ..
            ./restructure.sh
      
      - uses: actions/upload-artifact@v2
        with:
          name: kivy-output
          path: ./output

  create_package:
    name: Create Package
    runs-on: ubuntu-latest
    needs: [toolchainBuild]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: kivy-output
      - run: |
            chmod 755 create_package.sh
            ./create_package.sh
            

            zip -r package.zip Kivy-iOS-Package/*
            zip -r python_lib.zip python_lib/*
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Kivy-iOS-Package/"
          tag: "0.0"
          token: ${{ secrets.Homebrew }}
          #allowUpdates: true
